#pragma once
#ifndef S3_GAME_LOGIC_S3_EVENT_HPP
#define S3_GAME_LOGIC_S3_EVENT_HPP

namespace s3 {

enum class Event : uint8_t {
	NONE,
	STATE_CHANGE,
	GAME_OVER,
	SHIFT_INITIATED,

	OBJECT_EATEN_LATE,
	OBJECT_EATEN_LATE_SHIFT,
	OBJECT_EATEN,
	OBJECT_EATEN_SHIFT,

	BONUS_OBJECT_ADDED,
	BONUS_OBJECT_EATEN,
	BONUS_OBJECT_EATEN_SHIFT,
	BONUS_OBJECT_MISSED,
};

} // namespace s3

#endif